import edu.rit.ds.RemoteEvent;

/**
 * class GPSOfficeEvent represents an Event generated by the GPS office
 * 
 * @author Punit
 * 
 */
public class GPSOfficeEvent extends RemoteEvent {

	private String officeName;
	private long trackingId;
	private double x;
	private double y;
	private int status;

	/**
	 *  Returns the GPS office name
	 * @return office name
	 */
	public String getOfficeName() {
		return officeName;
	}

	/**
	 * Sets the GPS office name
	 * @param officeName office name to be set
	 */
	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

	/**
	 * Returns the GPS office delivery status
	 * @return status 
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * Sets the GPS office delivery status
	 * @param sets the status
	 */
	public void setStatus(int status) {
		this.status = status;
	}

	/**
	 * Returns the GPS office delivery tracking number
	 * @return tracking number
	 */
	public long getTrackingId() {
		return trackingId;
	}

	/**
	 * Sets the GPS Office delivery tracking number
	 * @param trackingId tracking number to be set
	 */
	public void setTrackingId(long trackingId) {
		this.trackingId = trackingId;
	}

	/**
	 *  Returns X co-ordinate of the destination
	 * @return x co-ordinate
	 */
	public double getX() {
		return x;
	}

	/**
	 * Sets the x co-ordinate of the destination
	 * @param x x co-ordinate
	 */
	public void setX(double x) {
		this.x = x;
	}

	/**
	 * Returns Y co-ordinate of the destination
	 * @return y co-ordinate
	 */
	public double getY() {
		return y;
	}

	/**
	 * Sets the y co-ordinate of the destination
	 * @param y y co-ordinate
	 */
	public void setY(double y) {
		this.y = y;
	}

	/**
	 * @param office
	 * @param id
	 * @param xCoord
	 * @param yCoord
	 * @param status
	 */
	public GPSOfficeEvent(String office, long id, double xCoord, double yCoord,
			int status) {

		officeName = office;
		trackingId = id;
		x = xCoord;
		y = yCoord;
		this.status = status;
	}

}
